### ISSUE TITLE
Adicionar suporte a arm64 no goreleaser

### ISSUE THREAD

**Issue by andrefrco** [dosedetelemetria/projeto-otel-na-pratica#13]
**Descrição**

Atualmente estou rodando nossas aplicações utilizando o minikube com o manifesto [kubernetes.yaml](https://github.com/dosedetelemetria/projeto-otel-na-pratica/blob/main/deployments/kubernetes.yaml). Ao adicionar a instrumentação automática pelo operator o container do otel não conseguiu identificar o binário da aplicação. Veja o log do autoinstrumentation:
```
{"level":"ERROR","msg":"failed to create instrumentation","error":"not a Go executable"}
```
Ao subir um container de debug, consegui identificar o processo do app
```
/ # ps aux
PID   USER     TIME  COMMAND
   14 root      0:00 {subscriptions} /usr/bin/qemu-x86_64 /subscriptions /subscriptions
   26 root      0:00 /otel-go-instrumentation
   40 root      0:00 bin/sh
   62 root      0:00 sleep 30
   ```
Mesmo com o apontamento para o binário estando correto no deployment do app:
```
annotations:
  instrumentation.opentelemetry.io/inject-go: "true"
  instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/subscriptions"
```

O fato do processo estar usando o qemu significa que a imagem está compilada em amd64, porém o minikube é executado em arm64 em processadores apple silicon.

**Passos para Reproduzir ou Detalhes da Sugestão**

Para corrigir esse problema pode adicionar a arch no goreleaser como o exemplo abaixo:
```
builds:
  - id: subscriptions
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - id: subscriptions
    image_templates:
      - "ghcr.io/dosedetelemetria/projeto-otel-na-pratica/subscriptions:latest"
      - "ghcr.io/dosedetelemetria/projeto-otel-na-pratica/subscriptions:{{ .Tag }}"
      - "ghcr.io/dosedetelemetria/projeto-otel-na-pratica/subscriptions:v{{ .Major }}"
    ids:
      - subscriptions
    dockerfile: "./cmd/subscriptions/Dockerfile"
    platforms:
      - linux/amd64
      - linux/arm64
```

Depois de alterando usando o `docker buildx` poderemos gerar a imagem multiarch.

**Impacto Esperado**

Auto instrumentação Go deve ser capaz de encontrar e instrumentar o binário da aplicação, enviando os traces para o endpoint de exporter sem erros em ambientes arm64.
