### ISSUE TITLE
Ingress Controller para acessar os serviços 

### ISSUE THREAD

**Issue by joaochiroli** [dosedetelemetria/projeto-otel-na-pratica#9]
Ao implantar meu projeto em um cluster Kubernetes na Azure, configurei um Ingress para gerenciar o acesso externo a todos os serviços do ambiente. Abaixo, descrevo os passos que segui:

 
Verificando em que resource group está o node do cluster kubernetes
```
az aks show --resource-group projeto-flask --name k8scluster --query nodeResourceGroup -o tsv
```
Criação do External IP

```
az network public-ip create --resource-group MC_projeto-flask_k8scluster_eastus --name myAKSPublicIPForIngress --sku Standard --allocation-method static --query publicIp.ipAddress -o tsv
```

Adicionando o repo

```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
```

Instalação do Ingress
```
helm install ingress-nginx ingress-nginx/ingress-nginx \
    --set controller.replicaCount=2 \
    --set controller.nodeSelector."kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.service.externalTrafficPolicy=Local \
    --set controller.service.loadBalancerIP="<ipexterno>" 
```

Edição do arquivo de deployments/kubernetes.yaml colocando a configuração do Ingress

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
     kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: users
            port:
              number: 8081
      - path: /plans
        pathType: Prefix
        backend:
          service:
            name: plans
            port:
              number: 8082
      - path: /subscriptions
        pathType: Prefix
        backend:
          service:
            name: subscriptions
            port:
              number: 8083
      - path: /payments
        pathType: Prefix
        backend:
          service:
            name: payments
            port:
              number: 8084
```

Executar

```
kubectl deploy -f kubernetes.yaml
```

Teste
```
http://<ipexterno>/payments
```
